name: Unit Testing

on: push

jobs:
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 'latest'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Test
        run: npm test

        env: 
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
